// <auto-generated />
using System;
using DeNew.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeNew.Migrations
{
    [DbContext(typeof(DeContext))]
    [Migration("20190104093229_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeNew.Models.Entities.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias");

                    b.Property<string>("Content");

                    b.Property<string>("Description");

                    b.Property<string>("ImageName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Keywords");

                    b.Property<string>("MetaDescription");

                    b.Property<string>("Name");

                    b.Property<int>("OrderNum");

                    b.Property<int?>("ParentPageId");

                    b.HasKey("Id");

                    b.HasIndex("ParentPageId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("DeNew.Models.Entities.Page", b =>
                {
                    b.HasOne("DeNew.Models.Entities.Page", "ParentPage")
                        .WithMany("SubPages")
                        .HasForeignKey("ParentPageId");
                });
#pragma warning restore 612, 618
        }
    }
}
